version: "3.8"

services:
  mysql:
    image: mysql:8.0.41
    container_name: mysql_music
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: musicdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./server
    container_name: backend_music
    restart: always
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: musicdb
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: ./client
    container_name: frontend_music
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mysql_data:
